// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuhbosagugeuwcwujqlw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1aGJvc2FndWdldXdjd3VqcWx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDk5NDEsImV4cCI6MjA1OTc4NTk0MX0.BHsGMuRV2RZqkaO9M_am3Z2mR-IEVvD7sK9XYgD8Xgc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);